(a)

CREATE TABLE Product(
maker CHAR(25) NOT NULL,
model CHAR(15) PRIMARY KEY,
type CHAR (25) NOT NULL
);

(b)

CREATE TABLE PC(
model CHAR(15) PRIMARY KEY,
speed DECIMAL(4,2) NOT NULL,
ram INTEGER NOT NULL,
hd INTEGER NOT NULL,
price DECIMAL (7,2) NOT NULL
);


(c)
CREATE TABLE Laptop(
model CHAR (15) PRIMARY KEY,
speed DECIMAL(4,2) NOT NULL,
ram INTEGER NOT NULL,
screen DECIMAL (3,1) NOT NULL,
price DECIMAL(7,2) NOT NULL
);

(d)

CREATE TABLE Printer(
model CHAR (15) PRIMARY KEY,
color BIT NOT NULL,
type CHAR (10) NOT NULL,
price DECIMAL(7,2) NOT NULL
);
